[[releases]]
version = "0.3.0"
date = "2026-02-24"
refs = [
    "WI-2026-02-24-001",
    "WI-2026-02-24-002",
    "WI-2026-02-24-003",
    "WI-2026-02-24-004",
    "WI-2026-02-24-005",
    "WI-2026-02-24-006",
]
