[[releases]]
version = "0.3.2"
date = "2026-03-01"
refs = ["WI-2026-03-01-002"]

[[releases]]
version = "0.3.1"
date = "2026-03-01"
refs = ["WI-2026-03-01-001"]

[[releases]]
version = "0.3.0"
date = "2026-02-24"
refs = [
    "WI-2026-02-24-001",
    "WI-2026-02-24-002",
    "WI-2026-02-24-003",
    "WI-2026-02-24-004",
    "WI-2026-02-24-005",
    "WI-2026-02-24-006",
    "WI-2026-02-24-007",
    "WI-2026-02-24-008",
    "WI-2026-02-24-009",
    "WI-2026-02-24-010",
]
